### ISSUE TITLE
Review of the challenge data curation script

### ISSUE THREAD

**Issue by trberg** [data2health/DREAM-Challenge#18]
Jupyter notebook describing the curation of the data: https://github.com/data2health/DREAM-Challenge/tree/master/documentation

**Comment by tschaffter** [comment]
@trberg Do we already have a document that describes the curation protocol?

**Comment by tschaffter** [comment]
Need to be reviewed by:

- [ ] @tschaffter 
- [x] @yy6linda (validator)

**Comment by tschaffter** [comment]
I should be able to review this documentation today or tomorrow.

@yy6linda Can you please carefully review the Jupyter notebooks that Tim wrote to refined the datasets? This is a critical step to prevent the risk of having bugs affecting the curated data.

**Comment by yy6linda** [comment]
Sure, will do.

**Comment by yy6linda** [comment]
I will work on this today.

**Comment by yy6linda** [comment]
I can't run the code directly to validate it because I don't have access to the database. @trberg Shall we find a time to meet and go over the code on your machine.

**Comment by tschaffter** [comment]
@yy6linda Have you and @trberg met to review together the content of the curation script? Since we are still in the process of finalizing the preparation of the challenge data, I would recommend that you meet again to review the finalized script. This script should be then uploaded to Synapse staging and its location mentioned in the document where we describe the preparation of the data.

**Comment by yy6linda** [comment]
Not yet, but I will talk to Tim
